name: Test with Cypress
on:
  workflow_call:
jobs:
  cypress_test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout GitCode
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.15.0
          cache: npm

      - name: Run Cypress Test
        uses: cypress-io/github-action@v4
        with:
          command: npx cypress run
          browser: chrome
          start: npm start, npm run mocks
          wait-on: http://127.0.0.1:3100
